targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - "**/models/**.dart"

      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - "**/models/**.dart"
