targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - "**/models/**.dart"

      json_serializable:
        generate_for:
          include:
            - "**/models/**.dart"
